name: Docker Publish

on:
  release:
    type:
      - published

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: DockerHub Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ghcr Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/nginx-http2-brotli
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3.1.0
        with:
          push: true
          cache-from: type=gha
          # outputs: type=local
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}